// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGBurbZM2Ru23SjwqAHAu27ro7nvNRC-E',
    appId: '1:258171306303:web:cd7ae42caa7a780b3c138a',
    messagingSenderId: '258171306303',
    projectId: 'to-do-app-81f74',
    authDomain: 'to-do-app-81f74.firebaseapp.com',
    storageBucket: 'to-do-app-81f74.firebasestorage.app',
    measurementId: 'G-JYY0ZZ4FXP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHb1NUWb7uA-_R8YeA7MdAasnEzHfCLkA',
    appId: '1:258171306303:android:9c75defbd935f1d43c138a',
    messagingSenderId: '258171306303',
    projectId: 'to-do-app-81f74',
    storageBucket: 'to-do-app-81f74.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACnvaNREtH0pQdgDuO7Y7KBMNHZbwmO4s',
    appId: '1:258171306303:ios:cdff202259cf15d83c138a',
    messagingSenderId: '258171306303',
    projectId: 'to-do-app-81f74',
    storageBucket: 'to-do-app-81f74.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );
}
